FROM mongo

COPY . ./
CMD ["/script.sh"]
#CMD ["mongoimport", "--username=admin", "--password=password", "--host=mongodb", "--authenticationDatabase=admin", "--db=mydb", "--collection=Users", "--type=json", "--file=/mydb.Users.json", "--jsonArray"]
#CMD ["mongoimport", "--username=admin", "--password=password", "--host=mongodb", "--authenticationDatabase=admin", "--db=mydb", "--collection=Events", "--type=json", "--file=/mydb.Events.json", "--jsonArray"]