FROM mongo

COPY . ./
CMD ["mongoimport", "--username=admin", "--password=password", "--host=mongodb", "--authenticationDatabase=admin", "--db=mydb", "--collection=Users", "--type=json", "--file=/mydb.Users.json", "--jsonArray"]